#! /bin/zsh

mkdir src/js
mkdir src/html
mkdir src/_json
mkdir src/html/_include
mkdir gulpConfig
mkdir src/scss
mkdir src/scss/foundation
mkdir src/scss/layout
mkdir src/scss/mixin 
mkdir src/scss/object
mkdir src/scss/object/component
mkdir src/scss/object/project
mkdir src/scss/object/utility

touch src/scss/foundation/_base.scss
touch src/scss/foundation/_reset.scss
touch src/scss/layout/_footer.scss
touch src/scss/layout/_header.scss
touch src/scss/layout/_main.scss
touch src/scss/layout/_sidebar.scss
touch src/scss/mixin/_mixin.scss
touch src/scss/object/component/_button.scss
touch src/scss/object/component/_daialog.scss
touch src/scss/object/component/_grid.scss
touch src/scss/object/component/_media.scss
touch src/scss/object/component/_title.scss
touch src/scss/object/project/_articles.scss
touch src/scss/object/project/_comments.scss
touch src/scss/object/project/_gallery.scss
touch src/scss/object/project/_profile.scss
touch src/scss/object/utility/_align.scss
touch src/scss/object/utility/_cleafix.scss
touch src/scss/object/utility/_margin.scss
touch src/scss/object/utility/_position.scss
touch src/scss/object/utility/_size.scss
touch src/scss/object/utility/_text.scss
touch gulpConfig/config.js
touch gulpConfig/pulugin.js
touch gulpConfig/ejsBuild.js
touch gulpConfig/jsBuild.js
touch gulpConfig/imgBuild.js
touch gulpConfig/localServer.js
touch gulpConfig/sassBuild.js

touch src/html/index.ejs
touch src/html/_include/_footer.ejs
touch src/html/_include/_head.ejs
touch src/html/_include/_header.ejs
touch src/_json/_meta.json